name: Build Windows EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup Ninja and CMake
      uses: lukka/get-cmake@latest

    - name: Setup Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.0'
        host: 'windows'
        target: 'desktop'

    - name: Build project
      run: |
        mkdir build
        cd build
        cmake .. -G "Ninja" -DCMAKE_BUILD_TYPE=Release
        ninja

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: MCPE-Launcher-Windows
        path: build/
