name: Build Windows EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: minecraft-linux/mcpelauncher-ui-manifest
        submodules: recursive
        fetch-depth: 0

    - name: Setup MSVC Compiler
      uses: ilammy/msvc-dev-cmd@v1

    - name: Setup Ninja and CMake
      uses: lukka/get-cmake@latest

    - name: Setup Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        modules: 'qtwebengine'

    - name: Install PkgConfig
      run: choco install pkgconfiglite -y

    - name: Install Dependencies (vcpkg)
      run: vcpkg install zlib libzip curl protobuf openssl --triplet x64-windows

    - name: Build project
      run: |
        mkdir build
        cd build
        cmake .. -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake"
        ninja

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MCPE-Launcher-Windows
        path: build/
